const XLSX = require('xlsx'); const fs = require('fs');
const DL = 'C:/Users/marke/Downloads/';
const cc = process.argv[2] || 'us';
const files = fs.readdirSync(DL).filter(f => f.includes(`_all-keywords_${cc}_2026-09-03`) && f.endsWith('.xlsx'));
const all = new Map();
for (const f of files) { const wb = XLSX.readFile(DL+f); const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {header:1}); const h=rows[0]; const ki=h.indexOf('Keyword'), vi=h.indexOf('Volume'), di=h.indexOf('Keyword Difficulty'), ii=h.indexOf('Intent');
  for (const r of rows.slice(1)) { const k=String(r[ki]||'').toLowerCase().trim(); if(!k) continue; const v=+r[vi]||0; const ex=all.get(k); if(!ex||ex.v<v) all.set(k,{v,kd:+r[di]||0,i:r[ii]||''}); } }
console.log('total unique', all.size);
// debug: near
const near=[...all].filter(([k])=>k.includes('near')).sort((a,b)=>b[1].v-a[1].v).slice(0,8); console.log('DEBUG near:', near.map(([k,o])=>k+'('+o.v+')').join('; '));
const groups = { geo:/\b(near me|new york|nyc|los angeles|chicago|houston|dallas|austin|texas|florida|california|miami|atlanta|seattle|denver|boston|phoenix|san diego|san francisco|usa|united states|america|london|manchester|birmingham|uk|england|scotland)\b/,
 cost:/\b(cost|price|pricing|expensive|cheap|affordable|budget|rates|fee|fees)\b/, crm:/\bcrm\b/, landing:/landing page/, redesign:/redesign/, maintenance:/maintenance|maintain|manage/, responsive:/responsive|mobile/, smallbiz:/small business|smb|startup/, ecommerce:/ecommerce|e-commerce|shopify|woocommerce/, wordpress:/wordpress|wix|squarespace|webflow/, agency:/\b(agency|agencies|company|companies|firm|firms|consultant|consultants|expert|experts|freelancer|freelance|developer|developers|designer|designers)\b/, hire:/\b(hire|hiring|outsourc\w*|offshore|remote)\b/, ai:/\b(ai|chatgpt|gpt|ai overview\w*|generative|geo|aeo|answer engine|llm)\b/, tech:/schema|core web vitals|page speed|site speed|hreflang|crawl|index|sitemap|robots|canonical|https|ssl/, industry:/manufactur|healthcare|construction|retail|distribution|wholesale|logistics|accounting|hr\b|payroll|inventory|supply chain|nonprofit|real estate|law firm|dental|restaurant|hvac|plumb/, examples:/example|list of|types of|modules?/, implementation:/implement|migration|integration|rollout|deploy/, custom:/\bcustom\b|bespoke|tailor/, vs:/\bvs\b|versus|difference between|compared/, report:/report|kpi|metric|roi|track/, strategy:/strategy|strategies|plan\b|checklist|audit|basics|tips|beginner|guide|101/, };
for (const [g,re] of Object.entries(groups)) { const hits=[...all].filter(([k,o])=>re.test(k)&&o.v>=100).sort((a,b)=>b[1].v-a[1].v); const tot=hits.reduce((s,[,o])=>s+o.v,0); console.log(`\n## ${g}: ${hits.length} kws>=100, vol ${tot}\n`+hits.slice(0,45).map(([k,o])=>`${k} (${o.v}, kd${o.kd}, ${o.i})`).join(' | ')); }
